Controllers/TiposCuentasController.cs
using Dapper;
using ManejoPresupuesto.Models;
using ManejoPresupuesto.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;

namespace ManejoPresupuesto.Controllers {
    public class TiposCuentasController : Controller {
        private readonly ITiposCuentasRepository tiposCuentasRepository;
        private readonly IUsuarioRepository usuarioRepository;

        public TiposCuentasController(ITiposCuentasRepository tiposCuentasRepository, 
                                      IUsuarioRepository usuarioRepository) {
            this.tiposCuentasRepository = tiposCuentasRepository;
            this.usuarioRepository = usuarioRepository;
        }

        public IActionResult Crear() {

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Crear(TipoCuentaModel tipoCuenta) {
            if (!ModelState.IsValid) {
                return View(tipoCuenta);
            }

            tipoCuenta.UsuarioID = usuarioRepository.ObtenerUsuarioID();

            var existeTipoCuenta = await tiposCuentasRepository.ExisteTipoCuenta(tipoCuenta.Nombre, tipoCuenta.UsuarioID);

            if (existeTipoCuenta) {
                ModelState.AddModelError(nameof(tipoCuenta.Nombre), $"El nombre { tipoCuenta.Nombre } ya existe!");

                return View(tipoCuenta);
            }

            await tiposCuentasRepository.Crear(tipoCuenta);

            return RedirectToAction("Index");
        }

        /* Verifica la existencia de un tipo de cuenta desde JS */
        [HttpGet]
        public async Task<IActionResult> VerificaExistenciaTipoCuenta(string nombre) {
            var usuarioID = usuarioRepository.ObtenerUsuarioID();
            var existeTipoCuenta = await tiposCuentasRepository.ExisteTipoCuenta(nombre, usuarioID);

            if (existeTipoCuenta) {
                return Json($"¡El nombre { nombre } ya existe!");
            }

            return Json(true);
        }

        /* Listado de Tipos Cuentas por Usuario ID */
        public async Task<IActionResult> Index() {
            var usuarioID = usuarioRepository.ObtenerUsuarioID();
            var tiposCuentas = await tiposCuentasRepository.ObtenerListadoByUsuarioID(usuarioID);

            return View(tiposCuentas);
        }

        /* Recupera un tipo de cuenta para actualizar */
        [HttpGet]
        public async Task<ActionResult> Editar(int id) {
            var usuarioID = usuarioRepository.ObtenerUsuarioID();
            var tipoCuenta = await tiposCuentasRepository.ObtenerTipoCuentaById(id, usuarioID);

            if (tipoCuenta is null) {
                return RedirectToAction("NoEncontrado", "Home");
            }

            return View(tipoCuenta);
        }

        /* Actualiza un tipo de cuenta */
        [HttpPost]
        public async Task<ActionResult> Editar(TipoCuentaModel tipoCuenta) {
            var usuarioID = usuarioRepository.ObtenerUsuarioID();
            var tipoCuentaExiste = await tiposCuentasRepository.ObtenerTipoCuentaById(tipoCuenta.Id, usuarioID);

            if (tipoCuentaExiste is null) {
                return RedirectToAction("NoEncontrado", "Home");
            }

            await tiposCuentasRepository.ActualizarTipoCuenta(tipoCuenta);

            return RedirectToAction("Index");
        }

        /* Recupera un tipo de cuenta para borrar */
        [HttpGet]
        public async Task<IActionResult> Borrar(int id) {
            var usuarioID = usuarioRepository.ObtenerUsuarioID();
            var tipoCuenta = await tiposCuentasRepository.ObtenerTipoCuentaById(id, usuarioID);

            if (tipoCuenta is null) {
                return RedirectToAction("NoEncontrado", "Home");
            }

            return View(tipoCuenta);
        }

        /* Aplica el borrado de tipo cuenta */
        [HttpPost]
        public async Task<IActionResult> BorrarTipoCuenta(int id) {
            var usuarioID = usuarioRepository.ObtenerUsuarioID();
            var tipoCuenta = await tiposCuentasRepository.ObtenerTipoCuentaById(id, usuarioID);

            if (tipoCuenta is null) {
                return RedirectToAction("NoEncontrado", "Home");
            }

            await tiposCuentasRepository.BorrartipoCuenta(id);

            return RedirectToAction("Index");
        }

        /* Ordena el listado en base a como se mapean en el front */
        [HttpPost]
        public async Task<IActionResult> OrdenarTipoCuenta([FromBody] int[] ids) {
            var usuarioID = usuarioRepository.ObtenerUsuarioID();
            var tiposCuentas = await tiposCuentasRepository.ObtenerListadoByUsuarioID(usuarioID);
            var idsTiposCuentas = tiposCuentas.Select(x => x.Id);

            /* Verifica que los ids que se reciben sean del usuario */
            var idsTiposCuentasNoUser = ids.Except(idsTiposCuentas).ToList();

            if (idsTiposCuentasNoUser.Count > 0) {
                return Forbid();
            }

            var tiposCuentasOrdenados = ids.Select((val, index) => 
                                                    new TipoCuentaModel() { 
                                                        Id = val,
                                                        Orden = index + 1
                                                    }).AsEnumerable();

            await tiposCuentasRepository.OrdenarTiposCuentas(tiposCuentasOrdenados);

            return Ok();
        }
    }
}

Views/TiposCuentas/Borrar.cshtml
@model TipoCuentaModel

@{
    ViewData["Title"] = "Borrar Tipo Cuenta";
}

<h3 class="mb-3">¿Está seguro que desea borrar @Model.Nombre?</h3>

<form asp-action="BorrarTipoCuenta">
    <input type="hidden" asp-for="Id" />
    <button type="submit" class="btn btn-danger">Borrar</button>
    <a class="btn btn-info" asp-action="Index">Cancelar</a>
</form>

Views/TiposCuentas/Crear.cshtml
@model TipoCuentaModel

@{
    ViewData["Title"] = "Crear Tipo Cuenta";
}

<h1>Crear Tipo de Cuenta</h1>
<h5>El tipo de cuenta se referie a cómo podemos agrupar cuentas. 
    Ejemplo: Préstamos, TCD, etc.
</h5>

<div asp-validation-summary="ModelOnly" class="text-danger"></div>

<form asp-controller="TiposCuentas" asp-action="Crear">
    <div class="mb-3">
        <label asp-for="Nombre" class="form-label"></label>
        <input type="text" asp-for="Nombre" class="form-control" />
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-success">Crear</button>
    <a asp-action="Index" class="btn btn-danger">Cancelar</a>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Views/TiposCuentas/Editar.cshtml
@model TipoCuentaModel

@{
    ViewData["Title"] = "Editar Tipo Cuenta";
}

<h1>Editar Tipo Cuenta: @Model.Nombre</h1>

<div asp-validation-summary="ModelOnly" class="text-danger"></div>

<form asp-action="Editar">
    <input type="hidden" asp-for="Id" />
    <div class="mb-3">
        <label asp-for="Nombre" class="form-label"></label>
        <input type="text" asp-for="Nombre" class="form-control" />
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-success">Actualizar</button>
    <a asp-action="Index" class="btn btn-danger">Cancelar</a>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Views/TiposCuentas/Index.cshtml
@model IEnumerable<TipoCuentaModel>

@{
    ViewData["Title"] = "Tipos Cuentas";
}

<h1>Tipos de Cuentas
    <a asp-action="Crear" class="btn btn-success" style="float: right;">Crear Tipo Cuenta</a>
</h1>
<hr />
<h5>El tipo de cuenta se referie a cómo podemo agrupar cuentas. 
    Ejemplo: Préstamos, Tarjetas de Crédito, Tarjetas de Débito, Vales, etc.
</h5>




<table class="table table-hover">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody id="reordenable">
        @foreach (var tipoCuenta in Model) {
            <tr>
                <td>
                    @tipoCuenta.Nombre
                </td>
                <td>
                    <input type="hidden" value="@tipoCuenta.Id" class="ids">
                    <a class="btn btn-warning" asp-action="Editar" asp-route-id="@tipoCuenta.Id">
                        <i class="bi-pencil-fill"></i>
                        Editar
                        </a>
                    <a class="btn btn-danger" asp-action="Borrar" asp-route-id="@tipoCuenta.Id">
                        <i class="bi-trash-fill"></i>
                        Borrar
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts {
    <script>
        const urlOrdenar = '@Url.Action("ordenarTipoCuenta")';

        $(function() {
            $("#reordenable").sortable({
                stop: async function(e, ui) {
                    await actualizarOrdenes();
                }
            });

            async function actualizarOrdenes() {
                const ids = obtenetIdsElementos();
                await enviarIdsBackend(ids);
            }

            function obtenetIdsElementos() {
                const ids = $(".ids").map(function() {
                    return $(this).val();
                }).get();

                return ids;
            }

            async function enviarIdsBackend(ids) {
                var data = JSON.stringify(ids);

                await fetch(urlOrdenar, {
                    method: 'POST',
                    body: data,
                    headers: {
                        'Content-Type': 'application/json'
                    }
                });
            }
        })
    </script>
}